# -*- coding: utf-8 -*-
"""altair.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFF_51FdqOzelj0wRz1ajQbnBxlIc9xT
"""

import altair as alt
import pandas as pd
import numpy as np

from google.colab import files
files.upload()

import pandas as pd
data = pd.read_excel('AirQualityUCI.xlsx')
data['Time'] = data['Time'].astype(str)
data

alt.data_transformers.enable(max_rows=None)
chart = alt.Chart(data)

alt.Chart(data).mark_point().encode(
    x='Date:Q',
    y='NOx(GT):Q'
    #color='Origin',
    #tooltip='Name'
).interactive()

interval = alt.selection_interval()

scatter = alt.Chart(data).mark_point().encode(
    x='Time:Q',
    y='CO(GT):Q',
    color=alt.condition(interval, 'Date:N', alt.value('lightgray'))
).add_selection(
    interval
)

hist = alt.Chart(data).mark_bar().encode(
    x='count()',
    y='Date',
    color='Date'
).transform_filter(
    interval
)

scatter & hist

source = data

alt.Chart(source).mark_circle(size=60).encode(
    x='Date',
    y='O2(GT)',
    tooltip=['Date', 'average(CO(GT))', 'average(NO2(GT))']
).properties(
    width = 1000, height = 500
).interactive()