# -*- coding: utf-8 -*-
"""Data_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mW5ve2Ay86DXTdG9ZFx4y2mh-_s9vUqK

#**Report**
"""

from google.colab import files
files.upload()

"""#Importing modules"""

import pandas as pd
import matplotlib.pyplot as plt

"""# **About Dataset**
According to the CDC, heart disease is one of the leading causes of death for people of most races in the US (African Americans, American Indians and Alaska Natives, and white people). About half of all Americans (47%) have at least 1 of 3 key risk factors for heart disease: high blood pressure, high cholesterol, and smoking. Other key indicator include diabetic status, obesity (high BMI), not getting enough physical activity or drinking too much alcohol. Detecting and preventing the factors that have the greatest impact on heart disease is very important in healthcare. Computational developments, in turn, allow the application of machine learning methods to detect "patterns" from the data that can predict a patient's condition.

Originally, the dataset come from the CDC and is a major part of the Behavioral Risk Factor Surveillance System (BRFSS), which conducts annual telephone surveys to gather data on the health status of U.S. residents. As the CDC describes: "Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world.". The most recent dataset (as of February 15, 2022) includes data from 2020. It consists of 401,958 rows and 279 columns. The vast majority of columns are questions asked to respondents about their health status, such as "Do you have serious difficulty walking or climbing stairs?" or "Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes]". In this dataset, I noticed many different factors (questions) that directly or indirectly influence heart disease, so I decided to select the most relevant variables from it and do some cleaning so that it would be usable for machine learning projects.

#**Introduction**

Dataset used for the project is “Personal Key Indicators of Heart Disease” dataset from kaggle. The dataset contains 18 different features in total. 
The dataset is used to study the frequency of heart disease and its cause among people of US. For the data analysis purpose, pandas module from python is used. 
Data analytics techniques is been used to get the frequency of heart disease among people with different age group along with different disease. 
Also the data has been visualized using matplotlib module of python. Various functions are used from pandas library to analyse the data and achieve the objective.

Dataset URL: https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease?resource=download

#Reading dataset and storing in pandas dataframe
"""

df = pd.read_csv("Dataset.csv")
df.head(5)

df.shape

"""#Cleaning dataset"""

#Data dosn't require cleaning it dosen't contain any null values in our cass so simple cleaning was done 
df.dropna(inplace = True)
df = df.reset_index(drop = True)  #to reset index after cleaning data
df.head(5)

df.shape

"""Q1) What is the average BMI of the person having heart disease?"""

# format for getting sub dataframe of dataset with some constraint.
# subDataFrame = DataFrame.loc[constraint1 & constraint2 & constraint3 | constraint4] ; 
# "&" resemble  AND operation
# '|' resemble  OR operation
person_having_heart_disease = df.loc[df['HeartDisease']=='Yes'] #getting data of patients having heart disease
print('\nAvg BMI of person having heart disease = {:.2f}'.format(person_having_heart_disease['BMI'].mean())) # calculating and printing mean.

"""Q2) Percentage of people not having heart disease but having smoking and drinking habit"""

#getting data of patients where they have habbit of smoking, drinking but do not have heart disease
people_not_having_heart_disease = df.loc[(df['Smoking'] == 'Yes') & (df['AlcoholDrinking']=='Yes') & (df['HeartDisease']=='No')]

#For percentage [(Total patient not having heart disease) * 100] / (total patients)
print(round(len(people_not_having_heart_disease)*100/len(df),2), '%')

"""Q3) What is the average percentage of people having heart disease who had a stroke earlier and have difficlty in walking?"""

#getting records of patients who had stroke earlier and have difficulti in walking and having heart disease
# result = df.loc[had_stroke & have_difficulti_walking & have_heart_disease]
result3_df = df.loc[(df['Stroke'] == 'Yes') & (df['DiffWalking']=='Yes') & (df['HeartDisease'] == 'Yes')]
print(round(len(result3_df)*100/len(df),2),'%')

"""Q4) What is the age category having maximum aggerate of people with heart disease? solve by grouping the column?"""

df2 = df.copy(deep=True) #making copy of original dataframe
df2.HeartDisease.replace(('Yes','No'),(1,0), inplace = True) #replacing bool/string data with integer value YES -> 1 and NO -> 0
result4_df = df2[['HeartDisease','AgeCategory']].groupby('AgeCategory').mean() #making group of dataset on ageCategory and taking mean value of all data available in each group
print(result4_df.loc[result4_df['HeartDisease'] == max(result4_df['HeartDisease'])])

"""Q5) In the past 30 days, show wether person having heart disease who is sufferring from mental health disease. [Show result in decending order] """

df2 = df[['HeartDisease','MentalHealth']] #Extracting Columns needed from original dataframe
df2 = df2.sort_values(by = 'MentalHealth', ascending=False) #sorting in decending order
print(df2)

"""Q6) Display all age group having heart disease in ascending order."""

df2 = df.copy(deep=True)
df2.HeartDisease.replace(('Yes','No'),(1,0), inplace = True)
df2 = df2[['HeartDisease','AgeCategory']].groupby('AgeCategory').mean() ##making group of dataset on ageCategory and taking mean value of all data available in each group
print(df2.sort_values(by = 'HeartDisease', ascending=False)) #sorting in decending and printing

"""Q7) Display all age group having Physical health disease in Ascending order."""

df2 = df.copy(deep=True)
df2.HeartDisease.replace(('Yes','No'),(1,0), inplace = True)
df2 = df2[['PhysicalHealth','AgeCategory']].groupby('AgeCategory').mean() ##making group of dataset on ageCategory and taking mean value of all data available in each group
print(df2.sort_values(by = 'PhysicalHealth'))# Sorting in acsending order

"""Q8) Visualize in pie chart according to age group with the people having smoking habbit."""

df2 = df.copy(deep=True)
df2.Smoking.replace(('Yes','No'),(1,0), inplace = True)
df2 = df2[['Smoking','AgeCategory']].groupby('AgeCategory').mean() 
plott = df2.plot(kind='pie', y='Smoking', autopct='%1.1f%%', title='People with smoking habbit in each age group') #plotting pie chart on the group formed
plt.show() #displaying pie chart

"""Q9) using bar graph show the age group having percentage of people with heart disease"""

df2 = df.copy(deep=True)
df2.HeartDisease.replace(('Yes','No'),(1,0), inplace = True)
df2 = df2[['HeartDisease','AgeCategory']].groupby('AgeCategory').mean()
#Plotting bar graph with single data column to show increase in heart disease with increase in age.
plt2 = df2.plot(kind='bar', title='Ratio of people having disease in each age group', ylabel='HeartDisease',xlabel='AgeCategory', figsize=(6, 5))
plt.show()

"""Q10) Visualize the habbit of smoking and alcohol in each age group."""

df2 = df.copy(deep=True)
df2.AlcoholDrinking.replace(('Yes','No'),(1,0), inplace = True)
df2.Smoking.replace(('Yes','No'),(1,0), inplace = True)
df2 = df2[['Smoking','AlcoholDrinking','AgeCategory']].groupby('AgeCategory').mean()
#Plotting bar graph for multiple column in order to visualize habbit of people
plt3 = df2.plot(kind='bar', title='people with smoking and drinking habbit in each age group', ylabel=['Smoking','AlcoholDrinking'],xlabel='AgeCategory', figsize=(6, 5))
plt.show()

"""Q11) Visualize the habbit of amoking and alcohol drinking in each age group using line chart."""

df2 = df.copy(deep=True)
df2.AlcoholDrinking.replace(('Yes','No'),(1,0), inplace = True)
df2.Smoking.replace(('Yes','No'),(1,0), inplace = True)
df2 = df2[['Smoking','AlcoholDrinking','AgeCategory']].groupby('AgeCategory').mean()
#Plotting bar graph for multiple column in order to visualize habbit of people
plt3 = df2.plot(kind='line', title='people with smoking and drinking habbit in each age group', ylabel=['Smoking','AlcoholDrinking'],xlabel='AgeCategory', figsize=(6, 5))
plt.show()

"""# **Summary:**

Dataset “Personal Key Indicators of Heart Disease” from kaggle is the reduced dataset of “2020 annual CDC survey of 400k adults related to their health status”. 
On applying data analysis technique over this dataset, it has been observed that the person having heart disease has average BMI of 29.4 and out of this 0.74% of the people 
have the stroke earlier. It has also been observed that 3.92% of the people do not have heart problem but have smoking and drinking habit that means approximately 96% people 
who has heart disease have smoking and drinking habit. Majority of the heart disease patient are found to be above 65 in age while maximum percentage of patient 
with heart disease is found in age group greater than 80 years with 22.56 percent. From the data analysis of dataset, it has been observed that many people that 
have heart disease either met with a stroke earlier or have some physical or mental disease. From the data analysis it is clear that many people that do not maintain 
their health and have smoking and drinking habit suffer from heart disease.
According to the graph plotted, every age group has almost same percentage of heart patient but it is more observed in old age people. 
Also it has been observed that people prefer smoking more than drinking alcohol as more number of people are having a habit of smoking but not drinking. 


"""

